version: 2
updates:
  # Python backend dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"

  # Node root dependencies (package.json)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

  # Node frontend dependencies (frontend/package.json)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
