# Generated by Django 5.2.15 on 2026-07-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginattempt',
            name='login_source',
            field=models.CharField(choices=[('FRONTEND', 'Frontend'), ('BACKEND', 'Backend')], default='BACKEND', max_length=20),
        ),
    ]
